parameters:
    anh_tied_content.entity.tie.class: Anh\TiedContentBundle\Entity\PaperTie
    anh_tied_content.url_generator.listener.class: Anh\TiedContentBundle\EventListener\UrlGenerator
    anh_tied_content.tie.remove_listener.class: Anh\TiedContentBundle\EventListener\TieListener
    anh_tied_content.form.type.tie.class: Anh\TiedContentBundle\Form\PaperTieType
    anh_tied_content.paper_transformer.class: Anh\TiedContentBundle\Form\PaperToIdentifierTransformer
    anh_tied_content.filter.admin_parent_list.class: Anh\TiedContentBundle\Filter\ParentFilter
    anh_tied_content.filter.admin_child_list.class: Anh\TiedContentBundle\Filter\ChildFilter

services:
    anh_tied_content.bundle:
        class: Anh\TiedContentBundle\AnhTiedContentBundle
        factory_service: kernel
        factory_method: getBundle
        arguments:
            - 'AnhTiedContentBundle'
        tags:
            - { name: anh_admin.bundle }

    anh_tied_content.url_generator.listener:
        class: %anh_tied_content.url_generator.listener.class%
        arguments:
            - @anh_tied_content.tie.repository
            - %anh_tied_content.sections%
        tags:
            - { name: kernel.event_subscriber }

    anh_tied_content.tie.remove_listener:
        class: %anh_tied_content.tie.remove_listener.class%
        calls:
            - [ setContainer, [@service_container] ]
        tags:
            - { name: doctrine.event_subscriber }

    anh_tied_content.form.type.tie:
        class: %anh_tied_content.form.type.tie.class%
        arguments:
            - %anh_tied_content.entity.tie.class%
            - @anh_tied_content.paper_transformer
        tags:
            - { name: form.type, alias: anh_tied_content_form_type_tie }

    anh_tied_content.paper_transformer:
        class: %anh_tied_content.paper_transformer.class%
        arguments:
            - @anh_content.paper.repository

    anh_tied_content.filter.admin_parent_list:
        class: %anh_tied_content.filter.admin_parent_list.class%
        arguments:
            - %anh_content.entity.category.class%
            - %anh_content.sections%

    anh_tied_content.filter.admin_child_list:
        class: %anh_tied_content.filter.admin_child_list.class%
